---
- name: install docker
  hosts: Nexus
  become: true
  tasks:
   - name: copy the script
     copy:
      src: /home/ubuntu/nexus.sh
      dest: /home/ubuntu
      mode: 0777
   - name: run the script
     shell: /home/ubuntu/nexus.sh
